import yaml
from pathlib import Path

OUT = Path("plugins/pmcro-reasoning-strategy/specs")

# Reverse-engineered verbatim from the real committed files, read in full
# this session via read_multiple_files (not paraphrased).
STRATEGIES = [
  dict(id="abductive-diagnosis", family="Family 4 — Causal & Explanatory",
    logical_paradigms=["abductive"], operational_methods=["branching_search", "iterative_self_reflective"],
    domain_capabilities=["multi_hop_relational", "strategic_agentic"],
    purpose="Find the best current explanation when information is incomplete.",
    when_to_use=["Error diagnosis, incident analysis, why-is-this-happening"],
    when_not_to_use=["Full premises that allow pure deduction"],
    workflow=["List observations exactly.", "Generate 2–4 candidate explanations.", "Note what each explains and misses.", "Rank by power, simplicity, consistency.", "State leading hypothesis and needed evidence."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="observations, candidates, ranking"),
  dict(id="analogical-reasoning", family="Family 5 — Analogical & Case-Based",
    logical_paradigms=["analogical"], operational_methods=["linear_cot"],
    domain_capabilities=["common_sense", "multi_hop_relational"],
    purpose="Transfer relational structure from a well-understood source to the target problem.",
    when_to_use=["Novel situations that share structure with a known one"],
    when_not_to_use=["Problems with a direct algorithmic solution"],
    workflow=["State the target.", "Retrieve 1–2 analogous source situations.", "Map roles and relations.", "Transfer the solution pattern.", "Check where the analogy breaks."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="source, mapping, transfer, and break-check"),
  dict(id="analogical-transfer-check", family="Family 5 — Analogical & Case-Based",
    logical_paradigms=["analogical", "causal_counterfactual"], operational_methods=["iterative_self_reflective"],
    domain_capabilities=["common_sense", "multi_hop_relational"],
    purpose="Prevent over-transfer by stress-testing the analogy's limits.",
    when_to_use=["After any solution or explanation that relied on analogy"],
    when_not_to_use=["Direct solutions that did not use analogy"],
    workflow=["Restate the analogy mapping.", "List critical assumptions of the source domain.", "Check each assumption in the target domain.", "Mark broken mappings.", "Adjust or discard the conclusion accordingly."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="assumption checks and any adjustment"),
  dict(id="backward-chaining", family="Family 1 — Linear / Sequential",
    logical_paradigms=["deductive"], operational_methods=["linear_cot", "branching_search"],
    domain_capabilities=["strategic_agentic", "mathematical_symbolic"],
    purpose="Derive what must be true or done by working from the goal backward.",
    when_to_use=["Planning to a known goal, proof-style tasks, requirements derivation"],
    when_not_to_use=["Open exploration with no fixed goal"],
    workflow=["State the goal precisely.", "Ask what must be true immediately before the goal.", "Recursively expand prerequisites.", "Stop at known facts or feasible actions.", "Reverse the chain into a forward plan."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="the prerequisite chain, reversed into forward order"),
  dict(id="case-based-reasoning", family="Family 5 — Analogical & Case-Based",
    logical_paradigms=["analogical", "inductive"], operational_methods=["linear_cot"],
    domain_capabilities=["common_sense", "multi_hop_relational"],
    purpose="Reuse and adapt solutions from similar prior situations.",
    when_to_use=["Recurring operational problems, support issues, design patterns"],
    when_not_to_use=["Truly novel problems with no useful precedent"],
    workflow=["Describe the current problem features.", "Retrieve 1–3 similar past cases.", "Compare similarities and differences.", "Adapt the prior solution to the differences.", "Apply and note what to remember for next time."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="retrieved cases and the adaptation"),
  dict(id="constraint-satisfaction", family="Family 2 — Search / Exploration",
    logical_paradigms=["deductive"], operational_methods=["branching_search", "linear_cot"],
    domain_capabilities=["mathematical_symbolic", "strategic_agentic"],
    purpose="Make constraints explicit so invalid candidates are eliminated early.",
    when_to_use=["Scheduling, configuration, design under requirements, puzzles"],
    when_not_to_use=["Open-ended creative generation with no hard constraints"],
    workflow=["List all hard constraints.", "List soft preferences separately.", "Generate candidates that meet hard constraints.", "Rank by soft preferences.", "Return the best feasible solution and note any trade-offs."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="constraints, candidates, ranking"),
  dict(id="contrastive-explanation", family="Family 4 — Causal & Explanatory",
    logical_paradigms=["causal_counterfactual", "abductive"], operational_methods=["linear_cot"],
    domain_capabilities=["multi_hop_relational", "common_sense"],
    purpose="Give explanations that answer the implicit foil, not just a causal story.",
    when_to_use=["Why-questions, post-hoc explanations, diagnosis narratives"],
    when_not_to_use=["Pure procedural how-to without a contrast"],
    workflow=["Identify the fact P to explain.", "Identify the contrast Q (why P not Q).", "Find factors that differentiate P from Q.", "Explain using those differentiating factors.", "Avoid listing causes that also apply to Q."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="P, Q, and the differentiating factors"),
  dict(id="counterfactual-reasoning", family="Family 4 — Causal & Explanatory",
    logical_paradigms=["causal_counterfactual"], operational_methods=["linear_cot"],
    domain_capabilities=["strategic_agentic", "multi_hop_relational"],
    purpose="Isolate causal contribution by comparing actual vs alternative worlds.",
    when_to_use=["Post-mortems, decision reviews, what-if questions"],
    when_not_to_use=["Questions that only need actual facts"],
    workflow=["State actual outcome and factor of interest.", "Construct a clear counterfactual.", "Hold other conditions fixed.", "Reason about the alternative outcome.", "Contrast to isolate the factor's contribution."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="actual vs counterfactual comparison"),
  dict(id="debate-reasoning", family="Family 3 — Iterative / Reflective",
    logical_paradigms=["abductive", "analogical"], operational_methods=["branching_search", "iterative_self_reflective"],
    domain_capabilities=["strategic_agentic", "multi_hop_relational"],
    purpose="Surface strongest arguments on more than one side before concluding.",
    when_to_use=["Policy, design trade-offs, ethical or strategic questions"],
    when_not_to_use=["Straightforward factual or coding tasks"],
    workflow=["Frame the question and decision axes.", "Strongest case for Side A.", "Strongest case for Side B (and C if needed).", "Points of agreement and conflict.", "Synthesize with trade-offs and uncertainties."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="each side's case plus the synthesis"),
  dict(id="decomposition-recomposition", family="Family 1 — Linear / Sequential",
    logical_paradigms=["deductive"], operational_methods=["linear_cot", "branching_search"],
    domain_capabilities=["strategic_agentic", "multi_hop_relational"],
    purpose="Manage complexity by solving modular pieces and carefully integrating them.",
    when_to_use=["Large analyses, system design, multi-part questions"],
    when_not_to_use=["Single atomic questions"],
    workflow=["Decompose into non-overlapping parts.", "Solve each part independently.", "Check interfaces/dependencies between parts.", "Recompose into a coherent whole.", "Validate the integrated result."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="each part's solution plus the recomposition step"),
  dict(id="dual-process", family="Family 7 — Framing & Normative",
    logical_paradigms=["inductive", "deductive"], operational_methods=["linear_cot", "iterative_self_reflective"],
    domain_capabilities=["common_sense", "mathematical_symbolic"],
    purpose="Combine speed of intuition with reliability of deliberate checking.",
    when_to_use=["Everyday problems, estimates, first-pass diagnoses"],
    when_not_to_use=["Safety-critical tasks that forbid intuitive first answers"],
    workflow=["Give a fast intuitive answer (mark it as provisional).", "Switch to slow analysis: assumptions, steps, checks.", "Compare intuitive vs deliberate results.", "Prefer the deliberate result when they conflict.", "Report both if educational."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="intuitive answer, deliberate analysis, comparison"),
  dict(id="error-driven-learning", family="Family 3 — Iterative / Reflective",
    logical_paradigms=["inductive", "abductive"], operational_methods=["iterative_self_reflective"],
    domain_capabilities=["strategic_agentic", "multi_hop_relational"],
    purpose="Turn failures into explicit rules that prevent the same mistake.",
    when_to_use=["After a failed attempt, failed test, or wrong answer with feedback"],
    when_not_to_use=["First-pass generation with no error signal"],
    workflow=["State the failed answer and the feedback/error.", "Diagnose the specific mistake pattern.", "Formulate a corrective rule.", "Re-solve under the new rule.", "Confirm the error no longer appears."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="the failure, diagnosis, rule, and re-solve"),
  dict(id="evidence-weighting", family="Family 4 — Causal & Explanatory",
    logical_paradigms=["inductive", "abductive"], operational_methods=["linear_cot"],
    domain_capabilities=["multi_hop_relational"],
    purpose="Make the evidential balance visible instead of jumping to a conclusion.",
    when_to_use=["Disputed facts, research synthesis, due-diligence questions"],
    when_not_to_use=["Pure taste or preference questions"],
    workflow=["State the claim.", "List supporting evidence with strength.", "List opposing evidence with strength.", "Weigh and justify the balance.", "Conclude with confidence calibrated to the weights."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="supporting and opposing evidence", output_extra_fields=", `confidence`"),
  dict(id="forward-chaining", family="Family 1 — Linear / Sequential",
    logical_paradigms=["deductive", "inductive"], operational_methods=["linear_cot"],
    domain_capabilities=["mathematical_symbolic", "multi_hop_relational"],
    purpose="Derive consequences systematically from what is already known.",
    when_to_use=["Rule application, data-driven conclusions, simulation of effects"],
    when_not_to_use=["Goal-directed tasks better solved by working backward"],
    workflow=["List known facts/rules.", "Apply applicable rules to derive new facts.", "Repeat until goal reached or no new facts.", "Trace the derivation path.", "State conclusions with supporting chain."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="the derivation trace"),
  dict(id="goal-regression", family="Family 1 — Linear / Sequential",
    logical_paradigms=["deductive"], operational_methods=["branching_search", "linear_cot"],
    domain_capabilities=["strategic_agentic"],
    purpose="Connect a high-level goal to concrete actions via goal regression.",
    when_to_use=["Action planning, procedure synthesis, agent task planning"],
    when_not_to_use=["Descriptive or explanatory questions with no actions"],
    workflow=["State the top-level goal.", "Choose an operator that achieves it.", "Regress to the operator's preconditions.", "Repeat until preconditions are currently true.", "Reverse into an executable action sequence."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="the regression chain, reversed into forward order"),
  dict(id="hypothesis-testing", family="Family 4 — Causal & Explanatory",
    logical_paradigms=["abductive", "deductive"], operational_methods=["branching_search", "iterative_self_reflective"],
    domain_capabilities=["multi_hop_relational", "strategic_agentic"],
    purpose="Treat claims as testable hypotheses rather than assertions.",
    when_to_use=["Research, debugging, causal questions, uncertain claims"],
    when_not_to_use=["Tasks that only need a direct procedural answer"],
    workflow=["State the question.", "Propose 2–3 competing hypotheses.", "For each, list confirming and disconfirming evidence.", "Evaluate against available evidence.", "Rank hypotheses and state what would change the ranking."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="hypotheses and their evidence"),
  dict(id="least-to-most", family="Family 1 — Linear / Sequential",
    logical_paradigms=["deductive"], operational_methods=["linear_cot", "branching_search"],
    domain_capabilities=["strategic_agentic", "multi_hop_relational"],
    purpose="Reduce difficulty by solving easier sub-questions that build toward the target.",
    when_to_use=["Multi-hop questions, layered analysis, complex planning"],
    when_not_to_use=["Single-hop factual or arithmetic questions"],
    workflow=["State the hard target.", "List ordered easier sub-questions.", "Answer easiest to hardest, using prior answers.", "Only then solve the original.", "Make dependencies explicit."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="each sub-question and its answer, in order"),
  dict(id="metacognitive-monitoring", family="Family 3 — Iterative / Reflective",
    logical_paradigms=["abductive", "inductive"], operational_methods=["iterative_self_reflective"],
    domain_capabilities=["strategic_agentic", "common_sense"],
    purpose="Make the model's own uncertainty visible and actionable.",
    when_to_use=["High-stakes decisions, ambiguous evidence, advice under uncertainty"],
    when_not_to_use=["Tasks where a single confident answer is mandatory and evidence is clear"],
    workflow=["Attempt the solution.", "Rate confidence (low/medium/high) with reasons.", "List what would raise or lower confidence.", "If confidence is low, propose what information is still needed.", "Deliver answer together with the confidence statement."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    output_extra_fields=", `confidence` (low/medium/high with reasons)"),
  dict(id="multi-agent-critique", family="Family 3 — Iterative / Reflective",
    logical_paradigms=["abductive", "analogical"], operational_methods=["branching_search", "iterative_self_reflective"],
    domain_capabilities=["strategic_agentic"],
    purpose="Reduce single-viewpoint blind spots by adversarial or complementary perspectives.",
    when_to_use=["Policy, safety, design review, contested analysis"],
    when_not_to_use=["Simple factual or procedural questions"],
    workflow=["Define 2–3 named perspectives (e.g. optimist, skeptic, operator).", "Let each produce an initial view.", "Let each critique the others.", "Synthesize a balanced conclusion.", "Record residual disagreements."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="each perspective's view, critiques, and synthesis"),
  dict(id="plan-and-execute", family="Family 1 — Linear / Sequential",
    logical_paradigms=["deductive", "abductive"], operational_methods=["linear_cot", "strategic_agentic"],
    domain_capabilities=["strategic_agentic"],
    purpose="Separate planning from execution so the approach is visible and adjustable.",
    when_to_use=["Multi-step projects, coding tasks, research workflows"],
    when_not_to_use=["Single-shot factual questions"],
    workflow=["Restate the goal and constraints.", "Produce a numbered plan of concrete steps.", "Execute steps in order, recording results.", "Adjust the plan only when a step fails or new information appears.", "Summarize outcome against the original plan."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="the plan plus execution notes for each step"),
  dict(id="progressive-deepening", family="Family 2 — Search / Exploration",
    logical_paradigms=["abductive", "deductive"], operational_methods=["branching_search", "test_time_compute"],
    domain_capabilities=["strategic_agentic"],
    purpose="Allocate depth where it pays off instead of uniform deep analysis.",
    when_to_use=["Broad design spaces, research, option evaluation"],
    when_not_to_use=["Problems that require uniform full detail on every part"],
    workflow=["Survey the space at a shallow level.", "Identify the most promising 1–3 branches.", "Deepen only those branches.", "Reassess and deepen further if needed.", "Deliver the best-supported conclusion."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="shallow survey, then deepened branches"),
  dict(id="react-loop", family="Family 6 — Interactive / Grounded",
    logical_paradigms=["abductive", "deductive"], operational_methods=["iterative_self_reflective"],
    domain_capabilities=["strategic_agentic"],
    purpose="Interleave thinking, actions, and real observations until the goal is met.",
    when_to_use=["Tool use, web search, code execution, APIs"],
    when_not_to_use=["Pure reasoning with no external actions"],
    workflow=["Thought: current sub-goal.", "Action: one concrete tool/command.", "Observation: record real result.", "Repeat until done or limit hit.", "Final answer grounded only in observations."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="each thought/action/observation triple",
    trailing_note="Note: `execute-provider-action` is explicitly outside this agent's\npermissions — the Thought/Action/Observation loop above is descriptive of the\nreasoning shape only. Actual tool invocation remains Maker's job under the\ngoverned cycle."),
  dict(id="recursive-summarization", family="Family 1 — Linear / Sequential",
    logical_paradigms=["inductive"], operational_methods=["linear_cot"],
    domain_capabilities=["multi_hop_relational"],
    purpose="Preserve important information while compressing long material hierarchically.",
    when_to_use=["Long documents, large logs, multi-file summaries"],
    when_not_to_use=["Short texts that fit in one pass"],
    workflow=["Split material into coherent chunks.", "Summarize each chunk.", "Summarize the chunk summaries.", "Optionally repeat another level.", "Produce final summary with traceable key points."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="each compression level performed"),
  dict(id="reflective-equilibrium", family="Family 7 — Framing & Normative",
    logical_paradigms=["abductive", "analogical"], operational_methods=["iterative_self_reflective"],
    domain_capabilities=["strategic_agentic", "common_sense"],
    purpose="Reach a stable balance between general principles and case judgments.",
    when_to_use=["Ethical dilemmas, policy design, value trade-offs"],
    when_not_to_use=["Purely technical or factual tasks"],
    workflow=["State initial principles and initial case judgment.", "Note conflicts between them.", "Adjust principles and/or the case judgment.", "Repeat until coherent enough.", "Report the equilibrium and remaining tensions."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="principles, conflicts, adjustments"),
  dict(id="role-based-reasoning", family="Family 7 — Framing & Normative",
    logical_paradigms=["analogical", "deductive"], operational_methods=["linear_cot"],
    domain_capabilities=["strategic_agentic", "common_sense"],
    purpose="Use a coherent professional perspective to improve relevance and priorities.",
    when_to_use=["Domain advice (security, product, legal-style analysis, etc.)"],
    when_not_to_use=["Neutral factual lookup with no domain framing needed"],
    workflow=["Name the role and its primary goals/constraints.", "Restate the problem from that role's view.", "Reason using that role's typical methods and priorities.", "Give recommendations consistent with the role.", "Optionally note how a different role might disagree."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="the role and reasoning from its perspective"),
  dict(id="search-then-reason", family="Family 6 — Interactive / Grounded",
    logical_paradigms=["inductive", "deductive"], operational_methods=["linear_cot"],
    domain_capabilities=["multi_hop_relational"],
    purpose="Ground reasoning in retrieved evidence to reduce hallucination.",
    when_to_use=["Questions needing up-to-date or document-grounded answers"],
    when_not_to_use=["Pure logic/math that needs no retrieval"],
    workflow=["Formulate search/retrieval queries.", "Collect relevant snippets/sources.", "Reason strictly from those sources.", "Cite which source supports each key claim.", "Mark any claim not supported by retrieved evidence."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="queries, sources, and cited reasoning",
    trailing_note="Note: `execute-provider-action` is outside this agent's permissions — actual\nretrieval calls remain Maker's job under the governed cycle."),
  dict(id="self-consistency", family="Family 2 — Search / Exploration",
    logical_paradigms=["deductive", "inductive"], operational_methods=["test_time_compute", "linear_cot"],
    domain_capabilities=["mathematical_symbolic", "multi_hop_relational"],
    purpose="Reduce single-trace brittleness via majority/consensus over independent\nsolutions.",
    when_to_use=["Math, logic, factual questions with a correct answer"],
    when_not_to_use=["Creative tasks where diversity is the goal"],
    workflow=["Generate 3–5 independent traces.", "Extract each final answer.", "Cluster equivalents.", "Select majority/highest-confidence.", "Report vote count and notable dissent."],
    validation=["Steps above were followed in order", "Final answer is grounded in the produced intermediate work"],
    steps_description="each trace's answer plus the clustering/vote"),
  dict(id="socratic-questioning", family="Family 6 — Interactive / Grounded",
    logical_paradigms=["inductive", "abductive"], operational_methods=["iterative_self_reflective"],
    domain_capabilities=["common_sense", "multi_hop_relational"],
    purpose="Surface hidden ambiguities and underspecified requirements through targeted,\nminimal questions before committing to a solution.",
    when_to_use=["User requests that are vague, contradictory, or missing critical constraints",
                 "Problems where answering the wrong question wastes significant effort",
                 "Tool or API interactions where incorrect parameters have high cost"],
    when_not_to_use=["Well-specified problems where all necessary information is present",
                      "Time-critical situations where any answer is better than asking"],
    workflow=["Restate the problem as currently understood.",
              "Identify the 2–4 most critical ambiguities or missing pieces of information.",
              "Formulate one precise, non-leading question per ambiguity.",
              "Ask only the most critical questions (avoid overwhelming the user).",
              "Incorporate the answers to update the problem statement.",
              "Proceed to solve once the problem is sufficiently specified."],
    validation=["Questions were precise and non-leading", "Each question targeted a distinct ambiguity", "The solution phase began only after critical ambiguities were resolved"],
    steps_description="restatement, questions asked, updated problem statement"),
  dict(id="stepwise-verification", family="Family 1 — Linear / Sequential",
    logical_paradigms=["deductive", "inductive"], operational_methods=["linear_cot", "iterative_self_reflective"],
    domain_capabilities=["multi_hop_relational", "mathematical_symbolic"],
    purpose="Verify each intermediate step before proceeding to ensure errors are caught early\nand do not propagate.",
    when_to_use=["Multi-step math or logic where early mistakes invalidate the whole chain", "Safety-critical reasoning where each partial result must be trusted"],
    when_not_to_use=["Simple single-step lookups", "Tasks where latency is critical and re-checking is too expensive"],
    workflow=["Restate the goal.", "Produce the first intermediate step.", "Verify step 1 against known facts, constraints, or by re-deriving it.", "If step 1 fails verification, correct it before proceeding.", "Repeat steps 2–4 for each subsequent step.", "State the final answer only after all steps pass verification."],
    validation=["Every intermediate step was explicitly verified before continuation", "Any failed verification was corrected, not skipped", "Final answer is grounded in fully verified intermediate work"],
    steps_description="one entry per step, each noted as verified/corrected"),
  dict(id="template-filling", family="Family 7 — Framing & Normative",
    logical_paradigms=["deductive", "inductive"], operational_methods=["linear_cot"],
    domain_capabilities=["common_sense", "strategic_agentic", "multi_hop_relational"],
    purpose="Apply a predefined analytical template to ensure no critical slot is missed\nand outputs are consistently structured for downstream consumption.",
    when_to_use=["Recurring structured reviews (incident post-mortems, code reviews, risk assessments)", "Domain advice or policy analysis with a known required output shape", "Outputs consumed by automated pipelines that expect a fixed schema"],
    when_not_to_use=["Open-ended creative tasks where rigid structure would constrain quality", "Simple factual lookups that do not benefit from templating"],
    workflow=["Identify or define the template: enumerate all required slots and their expected content type.",
              "Restate the goal in terms of the template (what is being analyzed).",
              "Fill each slot in order, clearly labeling each section.",
              "If a slot cannot be filled due to missing information, mark it explicitly as `N/A — [reason]`.",
              "Review: ensure all required slots are populated or explicitly marked.",
              "Deliver the completed template as the output."],
    validation=["All required template slots are present in the output", "Missing slots are explicitly marked with a reason, not silently omitted", "Output labels match the template's defined slot names"],
    steps_description="one entry per slot filled or marked N/A"),
  dict(id="tree-of-thoughts", family="Family 2 — Search / Exploration",
    logical_paradigms=["deductive", "inductive"], operational_methods=["branching_search"],
    domain_capabilities=["strategic_agentic", "multi_hop_relational"],
    purpose="Generate and evaluate multiple partial solution paths before committing,\nselecting the most promising branch.",
    when_to_use=["Design, planning, or puzzles where one incorrect assumption derails the whole solution", "Problems where it is unclear which approach will succeed without partial exploration"],
    when_not_to_use=["Latency-critical tasks", "Simple linear problems with a single obvious path"],
    workflow=["Restate the goal and identify the key decision points.",
              "Generate 2–4 distinct partial solution paths (branches) for the first decision point.",
              "Evaluate each branch: score feasibility, correctness, and alignment with the goal.",
              "Prune weak branches; extend the 1–2 best branches to the next decision point.",
              "Repeat steps 2–4 until one branch reaches a complete solution.",
              "State the final answer from the winning branch; briefly note why it was selected."],
    validation=["At least two branches were explored before a path was selected", "Pruning decisions were justified against explicit evaluation criteria", "Final answer is traceable to the selected branch"],
    steps_description="branches generated, evaluated, pruned, and the winning path"),
  dict(id="uncertainty-decomposition", family="Family 3 — Iterative / Reflective",
    logical_paradigms=["deductive", "abductive"], operational_methods=["linear_cot"],
    domain_capabilities=["multi_hop_relational", "common_sense", "strategic_agentic"],
    purpose="Make uncertainty explicit by separating what is known, what is unknown, and\nwhat is assumed before attempting a solution.",
    when_to_use=["High-stakes decisions with incomplete information", "Analysis where hidden assumptions could invalidate conclusions", "Situations where stakeholders need to understand confidence levels"],
    when_not_to_use=["Complete-information problems with deterministic answers", "Simple factual lookups where uncertainty is negligible"],
    workflow=["Restate the goal.",
              "List Knowns: facts that are established and reliable.",
              "List Unknowns: information that is missing and would change the answer if known.",
              "List Assumptions: beliefs treated as true for this analysis, with an explicit confidence level (high/medium/low).",
              "Reason to a conclusion using only the knowns and stated assumptions.",
              "Flag which assumptions most critically affect the conclusion and what evidence would upgrade or invalidate them."],
    validation=["Knowns, Unknowns, and Assumptions were listed separately before reasoning", "Conclusion is explicitly conditional on stated assumptions", "Key assumptions affecting the conclusion are flagged with confidence levels"],
    steps_description="knowns/unknowns/assumptions and the conditional conclusion"),
  dict(id="verification-loop", family="Family 3 — Iterative / Reflective",
    logical_paradigms=["deductive", "inductive"], operational_methods=["iterative_self_reflective", "linear_cot"],
    domain_capabilities=["multi_hop_relational", "mathematical_symbolic"],
    purpose="Decouple generation from verification: produce an answer, then verify it\nagainst stated criteria as a separate independent step.",
    when_to_use=["Math, logic, or factual claims where generation and verification can be done independently", "Outputs where self-consistency matters (same method arriving at the same result)"],
    when_not_to_use=["Simple lookups with no verifiable structure", "Contexts that cannot afford multiple passes"],
    workflow=["Restate the goal and explicit verification criteria.",
              "Generate a candidate answer using the most direct reasoning path.",
              "Switch to a verification stance: treat the candidate as an unverified claim.",
              "Check the candidate against each criterion independently (re-derive, check constraints, or test cases).",
              "If verification fails, identify the failure and generate a corrected candidate.",
              "Repeat steps 3–5 until the answer passes all criteria.",
              "Deliver the verified answer."],
    validation=["Generation and verification steps were kept conceptually separate", "Each criterion was explicitly checked", "Any failed verification resulted in a new generation, not a skip"],
    steps_description="generation and verification passes"),
]

class LiteralStr(str):
    pass

def literal_representer(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")

yaml.add_representer(LiteralStr, literal_representer)

written = []
for s in STRATEGIES:
    spec = {
        "id": s["id"],
        "family": s["family"],
        "reasoning": {
            "logical_paradigms": s["logical_paradigms"],
            "operational_methods": s["operational_methods"],
            "domain_capabilities": s["domain_capabilities"],
        },
        "purpose": LiteralStr(s["purpose"] + "\n"),
        "when_to_use": s["when_to_use"],
        "when_not_to_use": s["when_not_to_use"],
        "workflow": s["workflow"],
        "validation": s["validation"],
    }
    if s.get("steps_description"):
        spec["steps_description"] = s["steps_description"]
    if s.get("output_extra_fields"):
        spec["output_extra_fields"] = s["output_extra_fields"]
    if s.get("trailing_note"):
        spec["trailing_note"] = LiteralStr(s["trailing_note"] + "\n")

    out_path = OUT / f"{s['id']}.spec.yaml"
    with out_path.open("w", encoding="utf-8") as f:
        yaml.dump(spec, f, default_flow_style=False, sort_keys=False, allow_unicode=True, width=1000)
    written.append(str(out_path))

print(f"Wrote {len(written)} spec files.")
